version: "3.3"

services:
  api:
    build: .

    env_file:
      - '.env'
    ports:
      - "8000:8000"

    volumes:
      - ./:/var/www/html:delegated

    networks:
      - web
      - backend

  db:
    image: postgres:13.6-alpine

    restart: unless-stopped

    environment:
      - "POSTGRES_DB=demo"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=123"

    volumes:
      - ./data/db:/var/lib/postgresql/data


    ports:
      - "5432:5432"

    networks:
      - backend
      - web

  redis:
    image: "redis:alpine"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    volumes:
      - ./data/redis-data:/var/lib/redis
      - ./data/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master
    ports:
      - "6379:6379"

    networks:
      - backend
      - web


  mongo:
    image: mongo:5.0

    restart: unless-stopped

    volumes:
      - ./data/mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      - backend
      - web

networks:
  web:
    external: true
  backend:
    driver: bridge