version: '3.3'
services:
    api:
        build: .

        environment:
          - VIRTUAL_HOST=api.server.loc

        ports:
            - "5000:5000"

        volumes:
            - .:/code

        networks:
          - backend
          - proxy_proxy


networks:
  backend:
    driver: bridge
  proxy_proxy:
    external: true