version: '3.3'

services:
  api:
    image: ghcr.io/nano-it/royal-api:master
    volumes:
      - ./:/var/www/html:delegated
    networks:
      - web
      - backend

  postgres:
    image: postgres:alpine
    container_name: db
    restart: unless-stopped
    networks:
      - backend
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_DB=royal
      - POSTGRES_USER=royal

networks:
  web:
    external: true


