version: "3.3"

services:
  api:
    build: .
    container_name: api
    env_file:
      - '.env'
    ports:
      - "8000:8000"

    volumes:
      - ./:/var/www/html:delegated

    networks:
      - web
      - backend
  db:
    image: postgres:13.6-alpine
    container_name: pg-db
    restart: unless-stopped
    environment:
      - "POSTGRES_DB=demo"
      - "POSTGRES_USER=postgres"
      - "POSTGRES_PASSWORD=123"

    volumes:
      - ./data/db:/var/lib/postgresql/data

    networks:
      - backend

  redis:
    image: "redis:alpine"

    command: redis-server --requirepass sOmE_sEcUrE_pAsS

    volumes:
      - $PWD/redis-data:/var/lib/redis
      - $PWD/redis.conf:/usr/local/etc/redis/redis.conf

    environment:
      - REDIS_REPLICATION_MODE=master

    networks:
      - backend

networks:
  web:
    external: true
  backend:
    external: true