version: "3.3"

services:
  demo_api:
    build: .
    container_name: 'flask-api'

    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=web"
      # http settings
      - "traefik.http.routers.demo-api.rule=Host(`api.server.loc`)"
      - "traefik.http.routers.demo-api.entrypoints=web"
      # https settings
#      - "traefik.http.middlewares.tlsredirect.redirectscheme.scheme=https"
#      - "traefik.http.routers.demo-api.middlewares=tlsredirect"
#      - "traefik.http.routers.demo-api-secure.rule=Host(`<domain>`)"
#      - "traefik.http.routers.demo-api-secure.entrypoints=websecure"
#      - "traefik.http.routers.demo-api-secure.tls.certresolver=myresolver"
#      - "traefik.http.routers.demo-api-secure.tls=true"
      # custom headers settings
#      - "traefik.http.middlewares.testheader.headers.accessControlAllowHeaders=x-localization"

    expose:
      - 8081

    networks:
      - web
      - backend

networks:
  web:
    external: true
  backend:
    external: true

